exclude: 'build|third-party|.github'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: ['--branch=main']
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [
          '--max-line-length=88',
          '--ignore=E501,E203,E266,W503,E741',
          '--per-file-ignores=__init__.py:F401'
        ]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
